{
 "title": "Massive Medal Pusher",
 "description": "Statistics for Massive Medal Pusher",
 "tags": [
  "VRChat",
  "Dekapu"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "username",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"dekapu-log\",\r\n  tag: \"user\"\r\n)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 }, "options": { "content": "# Statistics" } },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 6, "y": 1 }, "options": { "content": "# Medals" } },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 14, "y": 1 }, "options": { "content": "# Skill Points (SP)" } },
  {
   "title": "Total Acquired",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Total Acquired Over TIme",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n"
    }
   ]
  },
  {
   "title": "Skill Point Use (SP) Over TIme",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sp_use\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n"
    }
   ]
  },
  {
   "title": "Today's Total Acquired",
   "type": "stat",
   "description": "Resets at 7pm est",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Asia/Tokyo\")\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1d, offset: -5h, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Current Medals Held",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"credit\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Medals/hr Trends",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
    }
   ]
  },
  {
   "title": "Skill Points (SP) Used/hr Trends",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sp_use\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
    }
   ]
  },
  {
   "title": "Play TIme",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"playtime\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Max medals/min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"cpm_max\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _value: float(v: math.floor(x: r._value))\r\n      }))\r\n"
    }
   ]
  },
  {
   "title": "Roulette Spins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"slot_start\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Fever Roulette Spins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"slot_getfev\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Roulette Wins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"slot_hit\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Fever Rotation (??)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"slot_startfev\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Acquisition Heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 14, "w": 8, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n      time: r._time,\r\n      value: r._value,\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Skill Point (SP) Use Heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 14, "w": 9, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sp_use\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n      time: r._time,\r\n      value: r._value,\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Sherbi Lottery Balls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"bstp_rwd\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Total Skill Points Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sp_use\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Total Number of Achievements",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"l_achieve_count\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Total Number of Tasks Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"task_cnt\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Number of Sherbis Rescued",
   "type": "stat",
   "description": "Cute sherbis you can save by clicking a button near spawn. Serves no purpose other than achievements.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"buy_shbi\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Total Unknown Currency",
   "type": "stat",
   "description": "Randomly awarded at a very low chance while playing. Currently serves no purpose except achievements.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"bbox_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Room Sherbis Interacted With",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"rmshbi_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Unknown Currency Acquisition Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"task_cnt\" or r._field == \"bbox_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if exists r.task_cnt and r.task_cnt != 0.0 \r\n              then float(v: r.bbox_all) / float(v: r.task_cnt) \r\n              else 0.0\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Acquisition Rate (medals/min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all_delta_1m\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\n  |> filter(fn: (r) => r._field == \"credit_all_delta_1m\")\n  |> filter(fn: (r) => r.user == \"${user}\")\n  |> movingAverage(n: 60)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Room Sherbis Interacted With/hr Trends",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"rmshbi_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
    }
   ]
  },
  {
   "title": "JACKPOT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Highest Sherbi Jackpot Starting Value",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_startmax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Highest Paletta Jackpot Starting Value",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_startmax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Paletta Balls Obtained",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Paletta Chances",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t1\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Double Chance\" }))"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t2\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Massive Chance\" }))"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t3\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Heavenly Chance\" }))"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t4\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Galaxy Chance\" }))\r\n"
      }
     ]
    },
    {
     "title": "Paletta Jackpot Winrate (Overall)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "jacksp = from(bucket: \"dekapu-log\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> rename(columns: {_value: \"jacksp_value\"})\r\n\r\npallot = from(bucket: \"dekapu-log\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> rename(columns: {_value: \"pallot_value\"})\r\n\r\njoin(tables: {jacksp: jacksp, pallot: pallot}, on: [\"user\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if exists r.pallot_value and r.pallot_value != 0.0\r\n              then float(v: r.jacksp_value) / float(v: r.pallot_value)\r\n              else 0.0,\r\n  }))\r\n"
      }
     ]
    },
    {
     "title": "Highest Sherbi Jackpot Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_totalmax_v2\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Highest Paletta Jackpot Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_totalmax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Golden Paletta Ball Drops",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"dc_palball_get_100\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Paletta Jackpots",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Single\" }))"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t1\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Double\" }))"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t2\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Massive\" }))"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t3\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Heavenly\" }))"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t4\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"Galaxy\" }))"
      }
     ]
    },
    {
     "title": "Paletta Ball Internal Stock",
     "type": "timeseries",
     "description": "If this has a value, it means you are acquiring paletta balls faster than the roulette wheel pays out.\n\nThis is not the internal stock value, just that you have additional balls stored. If the value is above 1, it may be that you rejoined while there were paletta balls in the internal stock.",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 46 },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> filter(fn: (r) => r._field == \"palball_get\" or r._field == \"pallot_lot_t0\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: r.palball_get - r.pallot_lot_t0\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"difference\")\r\n"
      }
     ]
    },
    {
     "title": "Number of Sherbi Jackpots",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Number of Paletta Jackpots",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Golden Paletta Ball Rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"dc_palball_get_100\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 \r\n              then float(v: r.dc_palball_get_100) / float(v: r.pallot_lot_t0) \r\n              else 0.0\r\n    }))\r\n"
      }
     ]
    },
    {
     "title": "Paletta Jackpot Win Rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t0\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"Single\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t0) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))\r\n"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t1\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"Double\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t1) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t2\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"Massive\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t2) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))\r\n"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t3\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"Heavenly\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t3) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))\r\n"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t4\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"Galaxy\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t4) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))\r\n"
      }
     ]
    },
    {
     "title": "Hourly Paletta Win Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "jacksp = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\" and r._field == \"jacksp_get_all\" and r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({r with _field: \"PJP獲得数\"}))\r\n\r\npallot = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\" and r._field == \"pallot_lot_t0\" and r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({r with _field: \"ボール獲得数\"}))\r\n\r\nratio = join(\r\n    tables: {jacksp: jacksp, pallot: pallot},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _field: \"PJP当選率\",\r\n      _value: if exists r._value_pallot and r._value_pallot != 0.0\r\n              then float(v: r._value_jacksp) / float(v: r._value_pallot)\r\n              else 0.0\r\n  }))\r\n\r\nunion(tables: [jacksp, pallot, ratio])\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"PJP当選率\")\r\n"
      }
     ]
    },
    {
     "title": "Sherbi Jackpot Chances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
      }
     ]
    },
    {
     "title": "Paletta Jackpot Chances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
      }
     ]
    }
   ]
  },
  {
   "title": "Sherbi Jackpot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Steps",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Ultimates",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ult_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Steps Per Hour",
     "type": "barchart",
     "description": "Higher Number -> Faster Laps",
     "gridPos": { "h": 9, "w": 5, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
      }
     ]
    },
    {
     "title": "Average Number of Laps Between Jackpots",
     "type": "barchart",
     "description": "Smaller numbers make it easier to keep an ultimate up. If it's close to 1, consider pale pink totem.",
     "gridPos": { "h": 9, "w": 5, "x": 11, "y": 44 },
     "targets": [
      {
       "query": "sqr = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> rename(columns: {_value: \"sqr_step\"})\r\n\r\njack = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> rename(columns: {_value: \"jack_get\"})\r\n\r\njoin(tables: {sqr: sqr, jack: jack}, on: [\"_time\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if r.jack_get > 0.0 \r\n              then float(v: r.sqr_step) / (float(v: r.jack_get) * 16.0) \r\n              else 0.0\r\n    }))\r\n"
      }
     ]
    },
    {
     "title": "Sherbi Lottery Balls and Steps",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
      },
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
      }
     ]
    },
    {
     "title": "Laps",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Ultimate Max Combo",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ult_combomax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Average Laps per Jackpot",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\" or r._field == \"jack_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if exists r.jack_get and r.jack_get > 0.0 \r\n              then float(v: r.sqr_step) / (float(v: r.jack_get) * 16.0) \r\n              else 0.0\r\n    }))\r\n"
      }
     ]
    },
    {
     "title": "Ultimate Max Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ult_totalmax_v2\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Totems",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Totem Placement",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^l_totems_set_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field:\r\n        if r._field == \"l_totems_set_1\" then \"Altar 1\"\r\n        else if r._field == \"l_totems_set_2\" then \"Altar 2\"\r\n        else if r._field == \"l_totems_set_3\" then \"Altar 3\"\r\n        else if r._field == \"l_totems_set_4\" then \"Altar 4\"\r\n        else if r._field == \"l_totems_set_5\" then \"Altar 5\"\r\n        else r._field,\r\n      _value:\r\n        if r._value == 0 then \"N/A\"\r\n        else if r._value == 1 then \"Orange\"\r\n        else if r._value == 2 then \"Green\"\r\n        else if r._value == 4 then \"Pink\"\r\n        else if r._value == 5 then \"Purple\"\r\n        else if r._value == 6 then \"White\"\r\n        else if r._value == 7 then \"Cyan\"\r\n        else if r._value == 8 then \"Pale Red\"\r\n        else if r._value == 9 then \"Navy\"\r\n        else if r._value == 10 then \"Red\"\r\n        else if r._value == 11 then \"Cream\"\r\n        else if r._value == 12 then \"Mint\"\r\n        else if r._value == 13 then \"Peach\"\r\n        else if r._value == 14 then \"Starry\"\r\n        else if r._value == 15 then \"Meadow\"\r\n        else if r._value == 16 then \"Black\"\r\n        else if r._value == 17 then \"Yellow\"\r\n        else if r._value == 18 then \"Lavender\"\r\n        else if r._value == 19 then \"Lime\"\r\n        else string(v: r._value)\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\"])\r\n"
      }
     ]
    },
    {
     "title": "Totem Use History",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 45 },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^l_totems_set_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field:\r\n        if r._field == \"l_totems_set_1\" then \"Altar 1\"\r\n        else if r._field == \"l_totems_set_2\" then \"Altar 2\"\r\n        else if r._field == \"l_totems_set_3\" then \"Altar 3\"\r\n        else if r._field == \"l_totems_set_4\" then \"Altar 4\"\r\n        else if r._field == \"l_totems_set_5\" then \"Altar 5\"\r\n        else r._field,\r\n      _value:\r\n        if r._value == 0 then \"N/A\"\r\n        else if r._value == 1 then \"Orange\"\r\n        else if r._value == 2 then \"Green\"\r\n        else if r._value == 4 then \"Pink\"\r\n        else if r._value == 5 then \"Purple\"\r\n        else if r._value == 6 then \"White\"\r\n        else if r._value == 7 then \"Cyan\"\r\n        else if r._value == 8 then \"Pale Red\"\r\n        else if r._value == 9 then \"Navy\"\r\n        else if r._value == 10 then \"Red\"\r\n        else if r._value == 11 then \"Cream\"\r\n        else if r._value == 12 then \"Mint\"\r\n        else if r._value == 13 then \"Peach\"\r\n        else if r._value == 14 then \"Starry\"\r\n        else if r._value == 15 then \"Meadow\"\r\n        else if r._value == 16 then \"Black\"\r\n        else if r._value == 17 then \"Yellow\"\r\n        else if r._value == 18 then \"Lavender\"\r\n        else if r._value == 19 then \"Lime\"\r\n        else string(v: r._value)\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
      }
     ]
    },
    {
     "title": "Acquisition & SP Use Heatmapped",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"date\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 10m, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n      time: r._time,\r\n      \"Medals Aqcuired\": r._value,\r\n  }))\r\n"
      },
      {
       "query": "import \"date\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sp_use\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 10m, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n      sp_time: r._time,\r\n      \"Skill Points (SP) Used\": r._value,\r\n  }))\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Sherbi Balls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sherbi Ball Dropped",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ball_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Balls Dropped",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 10, "x": 4, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_ball_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n          if r._field == \"dc_ball_get_0\" then \"Normal\"\r\n          else if r._field == \"dc_ball_get_1\" then \"Orange\"\r\n          else if r._field == \"dc_ball_get_2\" then \"Green\"\r\n          else if r._field == \"dc_ball_get_3\" then \"Rainbow\"\r\n          else if r._field == \"dc_ball_get_4\" then \"Pink\"\r\n          else if r._field == \"dc_ball_get_5\" then \"Purple\"\r\n          else if r._field == \"dc_ball_get_6\" then \"White\"\r\n          else if r._field == \"dc_ball_get_7\" then \"Cyan\"\r\n          else if r._field == \"dc_ball_get_8\" then \"Pale Pink\"\r\n          else if r._field == \"dc_ball_get_9\" then \"Navy\"\r\n          else if r._field == \"dc_ball_get_10\" then \"Red\"\r\n          else if r._field == \"dc_ball_get_11\" then \"Cream\"\r\n          else if r._field == \"dc_ball_get_12\" then \"Mint\"\r\n          else if r._field == \"dc_ball_get_13\" then \"Peach\"\r\n          else if r._field == \"dc_ball_get_14\" then \"Starry\"\r\n          else if r._field == \"dc_ball_get_15\" then \"Meadow\"\r\n          else if r._field == \"dc_ball_get_16\" then \"Black\"\r\n          else if r._field == \"dc_ball_get_17\" then \"Yellow\"\r\n          else if r._field == \"dc_ball_get_18\" then \"Lavender\"\r\n          else if r._field == \"dc_ball_get_19\" then \"Lime\"\r\n          else if r._field == \"dc_ball_get_90\" then \"Dead Sherbi (??)\"\r\n          else if r._field == \"dc_ball_get_91\" then \"Unknown Currency\"\r\n          else if r._field == \"dc_ball_get_100\" then \"Golden\"\r\n          else if r._field == \"dc_ball_get_101\" then \"Amethyst\"\r\n          else if r._field == \"dc_ball_get_102\" then \"Emerald\"\r\n          else if r._field == \"dc_ball_get_103\" then \"Rose Quartz\"\r\n          else if r._field == \"dc_ball_get_104\" then \"Topaz\"\r\n          else if r._field == \"dc_ball_get_105\" then \"Sapphire\"\r\n          else if r._field == \"dc_ball_get_334\" then \"Lottery\"\r\n          else if r._field == \"dc_ball_get_335\" then \"Lottery (Special)\"\r\n          else strings.replace(v: r._field, t: \"dc_ball_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n\r\n"
      }
     ]
    },
    {
     "title": "Ball Drop Rates",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\ndata = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_ball_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n          if r._field == \"dc_ball_get_0\" then \"Normal\"\r\n          else if r._field == \"dc_ball_get_1\" then \"Orange\"\r\n          else if r._field == \"dc_ball_get_2\" then \"Green\"\r\n          else if r._field == \"dc_ball_get_3\" then \"Rainbow\"\r\n          else if r._field == \"dc_ball_get_4\" then \"Pink\"\r\n          else if r._field == \"dc_ball_get_5\" then \"Purple\"\r\n          else if r._field == \"dc_ball_get_6\" then \"White\"\r\n          else if r._field == \"dc_ball_get_7\" then \"Cyan\"\r\n          else if r._field == \"dc_ball_get_8\" then \"Pale Pink\"\r\n          else if r._field == \"dc_ball_get_9\" then \"Navy\"\r\n          else if r._field == \"dc_ball_get_10\" then \"Red\"\r\n          else if r._field == \"dc_ball_get_11\" then \"Cream\"\r\n          else if r._field == \"dc_ball_get_12\" then \"Mint\"\r\n          else if r._field == \"dc_ball_get_13\" then \"Peach\"\r\n          else if r._field == \"dc_ball_get_14\" then \"Starry\"\r\n          else if r._field == \"dc_ball_get_15\" then \"Meadow\"\r\n          else if r._field == \"dc_ball_get_16\" then \"Black\"\r\n          else if r._field == \"dc_ball_get_17\" then \"Yellow\"\r\n          else if r._field == \"dc_ball_get_18\" then \"Lavender\"\r\n          else if r._field == \"dc_ball_get_19\" then \"Lime\"\r\n          else if r._field == \"dc_ball_get_90\" then \"Dead Sherbi (??)\"\r\n          else if r._field == \"dc_ball_get_91\" then \"Unknown Currency\"\r\n          else if r._field == \"dc_ball_get_100\" then \"Golden\"\r\n          else if r._field == \"dc_ball_get_101\" then \"Amethyst\"\r\n          else if r._field == \"dc_ball_get_102\" then \"Emerald\"\r\n          else if r._field == \"dc_ball_get_103\" then \"Rose Quartz\"\r\n          else if r._field == \"dc_ball_get_104\" then \"Topaz\"\r\n          else if r._field == \"dc_ball_get_105\" then \"Sapphire\"\r\n          else if r._field == \"dc_ball_get_334\" then \"Lottery\"\r\n          else if r._field == \"dc_ball_get_335\" then \"Lottery (Special)\"\r\n          else strings.replace(v: r._field, t: \"dc_ball_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n\r\ntotals = data\r\n  |> group(columns: [\"_time\"])\r\n  |> sum(column: \"_value\")\r\n  |> rename(columns: {_value: \"total\"})\r\n\r\njoin(\r\n  tables: {d: data, t: totals},\r\n  on: [\"_time\"]\r\n)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _field: r._field,\r\n      _value: float(v: r._value) / float(v: r.total) * 100.0\r\n  }))\r\n  |> group(columns: [\"_field\"])\r\n  \r\n"
      }
     ]
    },
    {
     "title": "Max Chain",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ball_chain\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Balls Dropped",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ball_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
      }
     ]
    },
    {
     "title": "Ball Drop Counts",
     "type": "stat",
     "gridPos": { "h": 7, "w": 10, "x": 4, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_ball_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n          if r._field == \"dc_ball_get_0\" then \"Normal\"\r\n          else if r._field == \"dc_ball_get_1\" then \"Orange\"\r\n          else if r._field == \"dc_ball_get_2\" then \"Green\"\r\n          else if r._field == \"dc_ball_get_3\" then \"Rainbow\"\r\n          else if r._field == \"dc_ball_get_4\" then \"Pink\"\r\n          else if r._field == \"dc_ball_get_5\" then \"Purple\"\r\n          else if r._field == \"dc_ball_get_6\" then \"White\"\r\n          else if r._field == \"dc_ball_get_7\" then \"Cyan\"\r\n          else if r._field == \"dc_ball_get_8\" then \"Pale Pink\"\r\n          else if r._field == \"dc_ball_get_9\" then \"Navy\"\r\n          else if r._field == \"dc_ball_get_10\" then \"Red\"\r\n          else if r._field == \"dc_ball_get_11\" then \"Cream\"\r\n          else if r._field == \"dc_ball_get_12\" then \"Mint\"\r\n          else if r._field == \"dc_ball_get_13\" then \"Peach\"\r\n          else if r._field == \"dc_ball_get_14\" then \"Starry\"\r\n          else if r._field == \"dc_ball_get_15\" then \"Meadow\"\r\n          else if r._field == \"dc_ball_get_16\" then \"Black\"\r\n          else if r._field == \"dc_ball_get_17\" then \"Yellow\"\r\n          else if r._field == \"dc_ball_get_18\" then \"Lavender\"\r\n          else if r._field == \"dc_ball_get_19\" then \"Lime\"\r\n          else if r._field == \"dc_ball_get_90\" then \"Dead Sherbi (??)\"\r\n          else if r._field == \"dc_ball_get_91\" then \"Unknown Currency\"\r\n          else if r._field == \"dc_ball_get_100\" then \"Golden\"\r\n          else if r._field == \"dc_ball_get_101\" then \"Amethyst\"\r\n          else if r._field == \"dc_ball_get_102\" then \"Emerald\"\r\n          else if r._field == \"dc_ball_get_103\" then \"Rose Quartz\"\r\n          else if r._field == \"dc_ball_get_104\" then \"Topaz\"\r\n          else if r._field == \"dc_ball_get_105\" then \"Sapphire\"\r\n          else if r._field == \"dc_ball_get_334\" then \"Lottery\"\r\n          else if r._field == \"dc_ball_get_335\" then \"Lottery (Special)\"\r\n          else strings.replace(v: r._field, t: \"dc_ball_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\"])\r\n"
      }
     ]
    },
    {
     "title": "Ball Drop Rate vs Yesterday",
     "type": "stat",
     "description": "Resets at 7pm est",
     "gridPos": { "h": 14, "w": 10, "x": 14, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"timezone\"\r\nimport \"strings\"\r\n\r\noption location = timezone.location(name: \"Asia/Tokyo\")\r\n\r\nball = from(bucket: \"dekapu-log\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\" and r._field == \"ball_get\" and r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1d, offset: -5h, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true)\r\n\r\nballs = from(bucket: \"dekapu-log\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\" and r._field =~ /^dc_ball_get_/ and r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1d, offset: -5h, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true)\r\n\r\njoin(\r\n  tables: {balls: balls, ball: ball},\r\n  on: [\"_time\"],\r\n)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _value: if r._value_ball == 0.0 then 0.0 else float(v: r._value_balls) / float(v: r._value_ball) * 100.0\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field_balls\", \"_value\"])\r\n  |> difference(nonNegative: false, columns: [\"_value\"])\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field_balls:\r\n          if r._field_balls == \"dc_ball_get_0\" then \"Normal\"\r\n          else if r._field_balls == \"dc_ball_get_1\" then \"Orange\"\r\n          else if r._field_balls == \"dc_ball_get_2\" then \"Green\"\r\n          else if r._field_balls == \"dc_ball_get_3\" then \"Rainbow\"\r\n          else if r._field_balls == \"dc_ball_get_4\" then \"Pink\"\r\n          else if r._field_balls == \"dc_ball_get_5\" then \"Purple\"\r\n          else if r._field_balls == \"dc_ball_get_6\" then \"White\"\r\n          else if r._field_balls == \"dc_ball_get_7\" then \"Cyan\"\r\n          else if r._field_balls == \"dc_ball_get_8\" then \"Pale Pink\"\r\n          else if r._field_balls == \"dc_ball_get_9\" then \"Navy\"\r\n          else if r._field_balls == \"dc_ball_get_10\" then \"Red\"\r\n          else if r._field_balls == \"dc_ball_get_11\" then \"Cream\"\r\n          else if r._field_balls == \"dc_ball_get_12\" then \"Mint\"\r\n          else if r._field_balls == \"dc_ball_get_13\" then \"Peach\"\r\n          else if r._field_balls == \"dc_ball_get_14\" then \"Starry\"\r\n          else if r._field_balls == \"dc_ball_get_15\" then \"Meadow\"\r\n          else if r._field_balls == \"dc_ball_get_16\" then \"Black\"\r\n          else if r._field_balls == \"dc_ball_get_17\" then \"Yellow\"\r\n          else if r._field_balls == \"dc_ball_get_18\" then \"Lavender\"\r\n          else if r._field_balls == \"dc_ball_get_19\" then \"Lime\"\r\n          else if r._field_balls == \"dc_ball_get_90\" then \"Dead Sherbi (??)\"\r\n          else if r._field_balls == \"dc_ball_get_100\" then \"Golden\"\r\n          else if r._field_balls == \"dc_ball_get_101\" then \"Amethyst\"\r\n          else if r._field_balls == \"dc_ball_get_102\" then \"Emerald\"\r\n          else if r._field_balls == \"dc_ball_get_103\" then \"Rose Quartz\"\r\n          else if r._field_balls == \"dc_ball_get_104\" then \"Topaz\"\r\n          else if r._field_balls == \"dc_ball_get_105\" then \"Sapphire\"\r\n          else if r._field_balls == \"dc_ball_get_334\" then \"Lottery\"\r\n          else if r._field_balls == \"dc_ball_get_335\" then \"Lottery (Special)\"\r\n          else strings.replace(v: r._field_balls, t: \"dc_ball_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n"
      }
     ]
    },
    {
     "title": "Max Ball Chain by Ball Type",
     "type": "stat",
     "gridPos": { "h": 7, "w": 10, "x": 4, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_ball_chain_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n          if r._field == \"dc_ball_chain_0\" then \"Normal\"\r\n          else if r._field == \"dc_ball_chain_1\" then \"Orange\"\r\n          else if r._field == \"dc_ball_chain_2\" then \"Green\"\r\n          else if r._field == \"dc_ball_chain_3\" then \"Rainbow\"\r\n          else if r._field == \"dc_ball_chain_4\" then \"Pink\"\r\n          else if r._field == \"dc_ball_chain_5\" then \"Purple\"\r\n          else if r._field == \"dc_ball_chain_6\" then \"White\"\r\n          else if r._field == \"dc_ball_chain_7\" then \"Cyan\"\r\n          else if r._field == \"dc_ball_chain_8\" then \"Pale Pink\"\r\n          else if r._field == \"dc_ball_chain_9\" then \"Navy\"\r\n          else if r._field == \"dc_ball_chain_10\" then \"Red\"\r\n          else if r._field == \"dc_ball_chain_11\" then \"Cream\"\r\n          else if r._field == \"dc_ball_chain_12\" then \"Mint\"\r\n          else if r._field == \"dc_ball_chain_13\" then \"Peach\"\r\n          else if r._field == \"dc_ball_chain_14\" then \"Starry\"\r\n          else if r._field == \"dc_ball_chain_15\" then \"Meadow\"\r\n          else if r._field == \"dc_ball_chain_16\" then \"Black\"\r\n          else if r._field == \"dc_ball_chain_17\" then \"Yellow\"\r\n          else if r._field == \"dc_ball_chain_18\" then \"Lavender\"\r\n          else if r._field == \"dc_ball_chain_19\" then \"Lime\"\r\n          else if r._field == \"dc_ball_chain_90\" then \"Dead Sherbi (??)\"\r\n          else if r._field == \"dc_ball_chain_100\" then \"Golden\"\r\n          else if r._field == \"dc_ball_chain_101\" then \"Amethyst\"\r\n          else if r._field == \"dc_ball_chain_102\" then \"Emerald\"\r\n          else if r._field == \"dc_ball_chain_103\" then \"Rose Quartz\"\r\n          else if r._field == \"dc_ball_chain_104\" then \"Topaz\"\r\n          else if r._field == \"dc_ball_chain_105\" then \"Sapphire\"\r\n          else if r._field == \"dc_ball_chain_334\" then \"Lottery\"\r\n          else if r._field == \"dc_ball_chain_335\" then \"Lottery (Special)\"\r\n          else strings.replace(v: r._field, t: \"dc_ball_chain_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\"])\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Medals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Medals Won",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"medal_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Medals Won By Type",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 10, "x": 4, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_medal_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n        if r._field == \"dc_medal_get_0\" then \"Normal\"\r\n        else if r._field == \"dc_medal_get_1\" then \"Orange (Roulette)\"\r\n        else if r._field == \"dc_medal_get_2\" then \"Green\"\r\n        else if r._field == \"dc_medal_get_3\" then \"Pink\"\r\n        else if r._field == \"dc_medal_get_4\" then \"Purple\"\r\n        else if r._field == \"dc_medal_get_5\" then \"Cyan\"\r\n        else if r._field == \"dc_medal_get_6\" then \"Wall Medal\"\r\n        else if r._field == \"dc_medal_get_7\" then \"SP Medal\"\r\n        else if r._field == \"dc_medal_get_12\" then \"Green x10\"\r\n        else if r._field == \"dc_medal_get_13\" then \"Pink x10\"\r\n        else if r._field == \"dc_medal_get_14\" then \"Purple x10\"\r\n        else if r._field == \"dc_medal_get_15\" then \"Gold\"\r\n        else if r._field == \"dc_medal_get_16\" then \"Gold Bar\"\r\n        else if r._field == \"dc_medal_get_17\" then \"Gold Bar x10\"\r\n        else if r._field == \"dc_medal_get_18\" then \"Large Gold\"\r\n        else if r._field == \"dc_medal_get_19\" then \"Large Gold x10\"\r\n        else if r._field == \"dc_medal_get_20\" then \"Large Gold x100\"\r\n        else if r._field == \"dc_medal_get_21\" then \"Unknown Currency\"\r\n        else if r._field == \"dc_medal_get_100\" then \"Rainbow\"\r\n        else if r._field == \"dc_medal_get_101\" then \"Gold (Bot Frame)\"\r\n        else if r._field == \"dc_medal_get_102\" then \"Sapphire\"\r\n        else if r._field == \"dc_medal_get_103\" then \"Ruby\"\r\n        else if r._field == \"dc_medal_get_104\" then \"Emerald\"\r\n        else if r._field == \"dc_medal_get_105\" then \"Diamond\"\r\n        else strings.replace(v: r._field, t: \"dc_medal_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n\r\n"
      }
     ]
    },
    {
     "title": "Medal Win Rates",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\ndata = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_medal_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field:\r\n        if r._field == \"dc_medal_get_0\" then \"Normal\"\r\n        else if r._field == \"dc_medal_get_1\" then \"Orange (Roulette)\"\r\n        else if r._field == \"dc_medal_get_2\" then \"Green\"\r\n        else if r._field == \"dc_medal_get_3\" then \"Pink\"\r\n        else if r._field == \"dc_medal_get_4\" then \"Purple\"\r\n        else if r._field == \"dc_medal_get_5\" then \"Cyan\"\r\n        else if r._field == \"dc_medal_get_6\" then \"Wall Medal\"\r\n        else if r._field == \"dc_medal_get_7\" then \"SP Medal\"\r\n        else if r._field == \"dc_medal_get_12\" then \"Green x10\"\r\n        else if r._field == \"dc_medal_get_13\" then \"Red x10\"\r\n        else if r._field == \"dc_medal_get_14\" then \"Purple x10\"\r\n        else if r._field == \"dc_medal_get_15\" then \"Gold\"\r\n        else if r._field == \"dc_medal_get_16\" then \"Gold Bar\"\r\n        else if r._field == \"dc_medal_get_17\" then \"Gold Bar x10\"\r\n        else if r._field == \"dc_medal_get_18\" then \"Large Gold\"\r\n        else if r._field == \"dc_medal_get_19\" then \"Large Gold x10\"\r\n        else if r._field == \"dc_medal_get_20\" then \"Large Gold x100\"\r\n        else if r._field == \"dc_medal_get_21\" then \"Unknown Currency\"\r\n        else if r._field == \"dc_medal_get_100\" then \"Rainbow\"\r\n        else if r._field == \"dc_medal_get_101\" then \"Gold (Bot Frame)\"\r\n        else if r._field == \"dc_medal_get_102\" then \"Sapphire\"\r\n        else if r._field == \"dc_medal_get_103\" then \"Ruby\"\r\n        else if r._field == \"dc_medal_get_104\" then \"Emerald\"\r\n        else if r._field == \"dc_medal_get_105\" then \"Diamond\"\r\n        else strings.replace(v: r._field, t: \"dc_medal_get_\", u: \"ID:\", i: 1)\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n\r\ntotals = data\r\n  |> group(columns: [\"_time\"])\r\n  |> sum(column: \"_value\")\r\n  |> rename(columns: {_value: \"total\"})\r\n\r\njoin(\r\n  tables: {d: data, t: totals},\r\n  on: [\"_time\"]\r\n)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _field: r._field,\r\n      _value: float(v: r._value) / float(v: r.total) * 100.0\r\n  }))\r\n  |> group(columns: [\"_field\"])\r\n"
      }
     ]
    },
    {
     "title": "Medals Inserted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"medal_in\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "title": "Medals Inserted per hour",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"medal_in\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
      }
     ]
    },
    {
     "title": "Medal Insertion Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 4, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"medal_in\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n"
      }
     ]
    },
    {
     "title": "Medals Won",
     "type": "stat",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_medal_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n        if r._field == \"dc_medal_get_0\" then \"Normal\"\r\n        else if r._field == \"dc_medal_get_1\" then \"Orange (Roulette)\"\r\n        else if r._field == \"dc_medal_get_2\" then \"Green\"\r\n        else if r._field == \"dc_medal_get_3\" then \"Pink\"\r\n        else if r._field == \"dc_medal_get_4\" then \"Purple\"\r\n        else if r._field == \"dc_medal_get_5\" then \"Cyan\"\r\n        else if r._field == \"dc_medal_get_6\" then \"Wall Medal\"\r\n        else if r._field == \"dc_medal_get_7\" then \"SP Medal\"\r\n        else if r._field == \"dc_medal_get_12\" then \"Green x10\"\r\n        else if r._field == \"dc_medal_get_13\" then \"Red x10\"\r\n        else if r._field == \"dc_medal_get_14\" then \"Purple x10\"\r\n        else if r._field == \"dc_medal_get_15\" then \"Gold\"\r\n        else if r._field == \"dc_medal_get_16\" then \"Gold Bar\"\r\n        else if r._field == \"dc_medal_get_17\" then \"Gold Bar x10\"\r\n        else if r._field == \"dc_medal_get_18\" then \"Large Gold\"\r\n        else if r._field == \"dc_medal_get_19\" then \"Large Gold x10\"\r\n        else if r._field == \"dc_medal_get_20\" then \"Large Gold x100\"\r\n        else if r._field == \"dc_medal_get_21\" then \"Unknown Currency\"\r\n        else if r._field == \"dc_medal_get_100\" then \"Rainbow\"\r\n        else if r._field == \"dc_medal_get_101\" then \"Gold (Bot Frame)\"\r\n        else if r._field == \"dc_medal_get_102\" then \"Sapphire\"\r\n        else if r._field == \"dc_medal_get_103\" then \"Ruby\"\r\n        else if r._field == \"dc_medal_get_104\" then \"Emerald\"\r\n        else if r._field == \"dc_medal_get_105\" then \"Diamond\"\r\n          else strings.replace(v: r._field, t: \"dc_medal_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\"])\r\n"
      }
     ]
    },
    {
     "title": "SP Medals Acquired",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"dc_medal_get_7\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
      }
     ]
    }
   ]
  }
 ]
}